name: Build Library

on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Run Build Job on Ubuntu
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Requirements
      run: sudo apt-get update -y && sudo apt-get install -y meson

    - name: Build Library and run Unit Tests
      run: meson setup build && meson compile -C build && meson test -C build

    - name: Install Library
      run: meson install -C build && sudo ldconfig

    - name: Build Examples
      run: cd examples && meson setup build && meson compile -C build

