name: Run Unittests

on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Run Build Job on Ubuntu
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Requirements
      run: sudo apt-get update -y && sudo apt-get install -y clang-tools libcmocka-dev

    - name: Run Unittests
      run: make tests

    - name: Check Formatting
      run: make format-check
